var THINGS_INVADERS_SAY = [
    "Noooo!",
    "They got Benny!",
    "Elist, they said. See the universe, they said.",
    "We have a cure for all diseases! We only want to impregnate 3% of your females!",
    "You damned dirty apes!",
    "We just want to deprogram you!",
    "We bring improvements for all humanity!",
    "These shields SUCK!",
    "What a mess!",
    "I sure miss my wife...",
    "Odds of human victory: 7,451 to 1",
    "Free your minds! Reeducation is the future!",
    "For the people!",
    "Have you seen these two droids?",
    "Accepting us will be a Great Leap Forward!",
    "Ouch!",
    "9 out of 10 earthlings welcome us!",
    "Oh crap...",
    "Stop shooting at me!",
    "Holy crap, we're all doing JUMPING JACKS!",
    "Why can't I activate my own shield?!",
    "Who designed these controls?!",
    "This human is a terrible shot but he's got lot's of ammo!",
    "By Grabthar's Hammer, by the sons of Warvan, you shall be avenged!",
    "Are we there yet?",
    "Hey, guys? There's a red, uh, thingy moving toward the green thingy.",
    "How adorable!",
    "Remember, go that way very fast. If something gets in your way, turn.",
    "I'm not going to die on this forsaken backwater planet!",
    "Dilithium chamber at maximum, Captain!",
    "What do you mean he's got 3 lives?!",
    "It's a trap!",
];